---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(osfr)

# 3-27 data
# analysis_plan <- osf_retrieve_file("7kpyn") %>%
#   osf_download()

f <- list.files("xml-data", full.names = T)
```

## Processing

```{r, echo = FALSE}

otherwise <- tibble(district_name = NA,
                    corona = NA, covid = NA,
                    link_found = NA, link = NA)

l <- map(f, possibly(proc_xml, otherwise))

proc_data <- map_df(l, ~.)

proc_data <- proc_data %>% 
  mutate(present = if_else(corona | covid, TRUE, FALSE))

o <- pull(proc_data, link)
proc_data$n_links <- map_int(o, length)

x <- proc_data %>% 
  mutate(state = str_sub(district_name, start = 10),
         state = str_split(state, "-")) %>% 
  pull(state)

proc_data$state <- map_chr(x, ~.[[1]]) %>% tolower() %>% tools::toTitleCase()

out_data <- proc_data %>% 
  janitor::tabyl(state, present) %>% 
  rename(not_present = `FALSE`,
         present = `TRUE`) %>% 
  mutate(prop_present = present / (present + not_present)) %>% 
  arrange(prop_present) %>% filter(state != "<NA>")

mean_n_links <- proc_data %>% 
  group_by(state) %>% 
  summarize(mean_n_links = mean(n_links))

to_plot <- out_data %>% 
  left_join(mean_n_links) %>% 
  rename(ID = state) %>% 
  mutate(ID = tolower(ID))

write_csv(to_plot, "to_plot.csv")

node <- osfr::osf_retrieve_node("https://osf.io/2txjy/")

# # update the data
# write_csv(select(proc_data, -link), "2020-03-28-processed-data.csv")
# 
# osfr::osf_upload(node, "2020-03-28-processed-data.csv", conflicts = "overwrite")


```

```{r}
split_name <- proc_data %>% 
  mutate(split_name = str_split(district_name, "-")) %>% 
  pull(split_name)

proc_data <- proc_data %>% 
  mutate(district_name = map_chr(split_name, ~.[3]),
         date = map_chr(split_name, ~str_c(.[5], "-", .[6], "-", .[7])),
         nces_id = map_chr(split_name, ~.[4]))

proc_data <- proc_data %>% 
  # mutate(state = str_split(state, "/"), 
  #        state = map_chr(state, ~.[2]),
  #        state = tools::toTitleCase(tolower(state)),
  #        date = str_split(date, "\\."),
  #        date = map_chr(date, ~.[1]),
  mutate(district_name = tools::toTitleCase(tolower(district_name)))

fin_data <- proc_data %>% 
  select(state, district_name, nces_id, corona, covid,  n_links, link)

tm <- read_csv("district-data.csv")

tm <- tm %>% 
  select(nces_id = `nces-id`,
         base_url = `website-url`)

fin_data <- fin_data %>% 
  left_join(tm) %>% 
  unnest(link) %>% 
  mutate(link = str_c(base_url, link)) %>% 
  select(state, district_name, nces_id, corona, covid, n_links, link)

sum_links <- fin_data %>% 
  filter(!is.na(link)) %>% 
  group_by(nces_id) %>% 
  summarize(links = toString(link))

```

```{r}
contains_ext <- function(x) {
  str_detect(x, "pdf") | str_detect(x, "png") | str_detect(x, "jpg") |
    str_detect(x, "doc") | str_detect(x, "docx") | str_detect(x, "xlsx")
}

my_lgl <- fin_data$link %>% 
  map_lgl(contains_ext)

scrape_me <- function(x, lgl, nces_id, today) {
  
  if (!lgl) {
    print(str_c(nces_id, ": html"))
    h <- read_html(x)
    write_xml(h, str_c(today,"/", nces_id, ".xml"))
  } else {
    ext <- tools::file_ext(x)
    print(str_c(nces_id, ": ", ext))
    download.file(x, destfile = str_c(today, "/",nces_id, ".", ext))
  }
}
```

```{r}
pmap(list(x = fin_data$link, lgl = contains_ext(fin_data$link), nces_id = fin_data$nces_id), possibly(scrape_me, NULL), today = "2020-03-30")
```

```{r}

final_data <- fin_data %>% 
  left_join(sum_links) %>% 
  select(-link) %>% 
  distinct(nces_id, .keep_all = T)

write_csv(final_data, "2020-03-28-processed-data.csv")

# update the data
write_csv(final_data, "2020-03-28-processed-data.csv")

osfr::osf_upload(node, "2020-03-28-processed-data.csv", conflicts = "overwrite")
```

## Plot by state

```{r, echo = FALSE}
library(sf)

US <- st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))

tp <- US %>% 
  left_join(to_plot)

p <- ggplot(tp) +
  geom_sf(aes(fill = prop_present)) +
  coord_sf(crs = st_crs(3347), default =TRUE) +
  theme_void() +
  theme(legend.position = "bottom", text = element_text(family = "Times", size = 18)) +
  scale_fill_continuous("Proportion of districts' websites referencing COVID-19 or Coronavirus")

p

ggsave("img/adoption-over-time.png", width = 11, height = 11)

states
```

# New plot

```{r}
context <- read_csv("ELSI_csv_export_637211822971983301773.csv", skip = 6)
context <- context %>% 
  rename(nces_id = `Agency ID - NCES Assigned [District] Latest available year`)

last_model <- final_data %>% 
  left_join(context)

edge <- read_excel("EDGE_GEOCODE_PUBLICLEA1819/EDGE_GEOCODE_PUBLICLEA_1819.xlsx")
edge <- rename(edge, nces_id = LEAID)

last_model <- last_model %>% 
  left_join(edge)
```

```{r}
tmm <- rename(last_model, latitude = LAT, longitude = LON)
tmm <- tmm %>% filter(!is.na(latitude) & !is.na(longitude))

mysf = st_as_sf(tmm, coords = c("longitude", "latitude"), 
                crs = 4326)

US <- st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))

p <- ggplot(data = mysf) +
  theme_void() + 
  geom_sf(data = US) +
  geom_sf() +
  coord_sf(crs = st_crs(3347), default =TRUE) 

mapview::mapview(p)

```
